kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: monitoring
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    nodePort: 32008
  selector:
    app: elasticsearch
