apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
  - name: centos
    image: k8s-registry.zeusis.com:32000/centos:7
    imagePullPolicy: Always
    command:
      - sleep
      - "3600"
