apiVersion: v1
kind: Pod
metadata:
  name: my-ubuntu
spec:
  nodeSelector:
    type: virtual
  containers:
  - name: my-ubuntu
    image: 10.0.12.203:32000/ubuntu:16.10
    imagePullPolicy: Always
    args:
    - -d
    securityContext:
      privileged: true
    ports:
    - containerPort: 2122
    volumeMounts:
    - name: ssh-key
      mountPath: /.ssh
      readOnly: true
  volumes:
  - name: ssh-key
    secret:
      secretName: ssh-key 
      #defaultMode: 0600
      items:
      - key: authorized-keys
        path: authorized_keys
