apiVersion: v1
kind: Service
metadata:
  name: drone-server
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 80
    nodePort: 32010
  selector:
    app: drone
    role: server
