apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone
  namespace: default
  labels:
    app: drone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
      - image: k8s-registry.zeusis.com:32000/drone:0.5
        name: drone-server
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: DRONE_OPEN
          value: "true"
        - name: DRONE_GITLAB
          value: "true"
        - name: DRONE_GITLAB_URL
          value: "http://dfx.zeusis.com:50073"
        - name: DRONE_GITLAB_GIT_USERNAME
          value: "dean.wu@zeusis.com"
        - name: DRONE_GITLAB_GIT_PASSWORD
          value: "trams007"
        - name: DRONE_SECRET
          value: "myselfkey"
        volumeMounts:
        - mountPath: /drone
          name: drone
      - image: drone/drone:0.5
        name: drone-agent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DRONE_SERVER
          value: "ws://127.0.0.1:80/ws/broker"
        - name: DRONE_SECRET
          value: "myselfkey"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker
      volumes:
      - name: drone
        hostPath:
          path: /var/lib/drone
      - name: docker
        hostPath:
          path: /var/run/docker.sock
