kind: Service
apiVersion: v1
metadata:
  name: hbase1
  namespace: development
  labels:
    app: hbase
spec:
  type: NodePort
  ports:
  - port: 50070
    name: hdfs
    nodePort: 30004
  - port: 8088
    name: yarn
    nodePort: 30005
  - port: 16010
    name: hbase
    nodePort: 30006
  - port: 8080
    name: spark
    nodePort: 30007
  selector:
  selector:
    app: hbase
---
kind: Service
apiVersion: v1
metadata:
  name: hbase
  namespace: development
  labels:
    app: hbase
spec:
  clusterIP: None
  ports:
  - port: 2122
    name: ssh
  selector:
    app: hbase
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: hbase
  namespace: development
spec:
  replicas: 3
  serviceName: hbase
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: hbase
    spec:
      nodeSelector:
        #type: dell-r610
        type: virtual
      terminationGracePeriodSeconds: 0
      containers:
      - name: hadoop
        image: 10.0.12.203:32000/hbase:1.2.001
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: 4000Mi
          requests:
            cpu: 2000m
            memory: 4000Mi
        ports:
        # hdfs
        - containerPort: 50010
        - containerPort: 50020
        - containerPort: 50070
        - containerPort: 50470
        - containerPort: 50075
        - containerPort: 50475
        - containerPort: 50090
        - containerPort: 8019
        - containerPort: 8020
        - containerPort: 8480
        - containerPort: 8485
        # mapred
        - containerPort: 10020
        - containerPort: 19888
        # yarn
        - containerPort: 8030
        - containerPort: 8031
        - containerPort: 8032
        - containerPort: 8033
        - containerPort: 8040
        - containerPort: 8042
        - containerPort: 8088
        # jobhistory
        - containerPort: 10020
        - containerPort: 19888
        # hbase
        - containerPort: 16010
        - containerPort: 16020
        - containerPort: 16030
        - containerPort: 60000
        - containerPort: 60010
        - containerPort: 60020
        - containerPort: 60030
        #- containerPort: 8080
        # hive
        - containerPort: 9083
        - containerPort: 10000
        # spark
        - containerPort: 8080
        - containerPort: 7077
        # zk
        - containerPort: 2181
        - containerPort: 2191
        - containerPort: 2192
        # ssh
        - containerPort: 2122
        securityContext:
          privileged: true
        env:
        - name: NAMESPACE
          value: "development"
        - name: SERVICE
          value: "hbase"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - -d
        volumeMounts:
        - name: ssh-key
          mountPath: /.ssh
          readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key 
          items:
          - key: authorized-keys
            path: authorized_keys
          - key: id-rsa
            path: id_rsa
          - key: id-rsa.pub
            path: id_rsa.pub
