kind: Service
apiVersion: v1
metadata:
  name: push-zookeeper
  namespace: development
  labels:
    type: push-zookeeper
spec:
  ports:
  - port: 2122
    name: ssh
  - port: 2181
    name: zk
  selector:
    type: push-zookeeper
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: push-zookeeper
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: push-zookeeper
    spec:
      nodeSelector:
        type: virtual
      containers:
      - name: push-zookeeper
        image: 10.0.12.203:32000/zookeeper:3.4.9.001
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        ports:
        # ssh
        - containerPort: 2122
        # zk
        - containerPort: 2181
        env:
        - name: AUTHORIZED_KEYS
          value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwUOUP6vVEeELZNKKm9mNPP2wl6tWjGfqJPHsfRuasa1uRGtWqgd2TbHqGc0tCUkqKivATVjgiGy2he/dwEoth2R3+2FdLSISv1l5acQnlhxxo79vA2gOa7dcoCInF0ajklDD/01f3QDyJ7qSmMLEMo5cYBkkN1KqujJkvx3CsiAVrUxseH3XhbCavlBlYpB/1QVOc8RKeEnhMSTJzW3tINRyLv8a3qh7O9kOKfzqKXwPOEYx+Ich3psvzcmslNxpX3b/4qEf0fLKba+IxrgNAXn/SJg9RIsxotLrIlRFWozWF+KYZf0NKuhF2kbzcTWgDUJAB6Z+3zsM1Sz3qZLkz k8s@k8s_m.kubernetes.com,ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqQR8+l71l7XFLaKfylK9u9goEYQjy6KW1TXY6wQCzIk2hNpUBzHdca5MLf70nrKl7qD/bFGXtC/W1qIYhayG2lCsfHZTBWQ665zlbxRvxwxPYovFeIE1+wG4WoUMa++oOUu97nqzOA8SA/gh14rj/poco5H4JUtdbbwBFIW8/9pchRSRhwKV7UdHj/kufeAAoE05y4s6ioJES1VOsnGUP6utwePUSD2pygslAZde8o1e5/q95LvGI7xCzQgV73U72Wp7T7Ri0YXobDfYfcVpcqPngqb6uAy6mpWX1kDT2LXDxn8kw7Sd2YIgLva4Xn6R8Jxa4jRVlSVpOmdmEaXNt k8s@k8s_n1.kubernetes.com"
