apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kapacitor-prd
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: kapacitor-prd
    spec:
      containers:
      - name: kapacitor
        image: k8s-registry.zeusis.com:32000/zs/kapacitor:1.2
        imagePullPolicy: Always
        env:
          - name: INFLUXDB_URLS
            value: "http://influxdb-prd:8086"
          - name: KAPACITOR_HOSTNAME
            value: kapacitor-prd
