kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kapacitor-storage-pvc-prd
  namespace: monitoring
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: monitoring-kapacitor-storage-pv-prd
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.72.157
    path: "/data/kapacitor-pv-prd"
