apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: kapacitor-prd
  name: kapacitor-prd
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: http
    port: 9092
    nodePort: 32011
  selector:
    k8s-app: kapacitor-prd
