kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-system-kube-registry-pv
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.12.203
    path: "/data/kube-registry-pv"
