kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv2
  labels:
    kubernetes.io/cluster-service: "true"
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.12.203
    path: "/data/pv2"
