apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: k8s-registry.zeusis.com:32000/zs/influxdb:1.2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-storage-pvc
