apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: mon
  labels:
    app: prometheus
    role: alertmanager
spec:
  replicas: 1
  template:
    metadata:
      name: alertmanager
      labels:
        app: prometheus
        role: alertmanager
    spec:
      containers:
      - name: alertmanager
        # image: prom/alertmanager:v0.6.1
        image: k8s-registry.zeusis.com:32000/alertmanager:v0.6.1
        args:
          - '-config.file=/etc/prometheus/alertmanager.yml'
        resources:
          requests:
            cpu: 50m
            memory: 50M
          limits:
            cpu: 50m
            memory: 50M
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
