apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: mon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - name: kube-state-metrics
        # image: apsm/kube-state-metrics:v0.5.0
        image: k8s-registry.zeusis.com:32000/kube-state-metrics:v0.5.0
        resources:
          requests:
            cpu: 15m
            memory: 100M 
          limits:
            cpu: 15m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: kube-state-metrics
  namespace: mon
  labels:
    app: kube-state-metrics
spec:
  ports:
  - name: kube-state-metrics
    port: 8080
    protocol: TCP
  selector:
    app: kube-state-metrics
