apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: mon
  labels:
    app: prometheus
    role: core
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
        role: core
    spec:
      containers:
      - name: prometheus
        # image: prom/prometheus:v1.6.1
        image: k8s-registry.zeusis.com:32000/prometheus:v1.6.1
        args:
          # - '-storage.tsdb.retention=6h'
          - '-storage.local.retention=24h'
          #- '-storage.local.target-heap-size=2GiB'
          - '-storage.local.target-heap-size=1300000000'
          - '-storage.local.path=./data'
          #- '-storage.local.path=/data'
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-alertmanager.url=http://alertmanager:9093'
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 1000m
            memory: 3G
          limits:
            cpu: 1000m
            memory: 3G
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config-volume
        - mountPath: /etc/prometheus-rules
          name: rules-volume
        #- mountPath: /data
        #  name: prometheus-storage
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: rules-volume
        configMap:
          name: prometheus-rules
      #- name: prometheus-storage
      #  persistentVolumeClaim:
      #    claimName: prometheus-storage-pvc-prd
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: mon
  labels:
    app: prometheus
    role: core
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 32012
      protocol: TCP
      name: webui
  selector:
    app: prometheus
    role: core
