kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage-pvc-prd
  namespace: mon
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mon-prometheus-storage-pv-prd
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.72.157
    path: "/data/prometheus-pv-prd"
