apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        # image: kubernetes/heapster:canary
        image: k8s-registry.zeusis.com:32000/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:http://192.168.72.40:6550?inClusterConfig=false
        - --sink=influxdb:http://monitoring-influxdb.kube-system.svc.zeusis.local:8086
