kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-node
  namespace: default
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    name: es
    nodePort: 32004
  selector:
    app: elasticsearch
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  ports:
  - port: 2122
    name: ssh
  - port: 9200
    name: es-port
  - port: 9300
    name: es-cluster
  selector:
    app: elasticsearch
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  serviceName: elasticsearch
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: elasticsearch
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: elasticsearch
        image: k8s-registry.zeusis.com:32000/elasticsearch:5.1.001
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
        securityContext:
          privileged: true
        env:
        - name: NAMESPACE
          value: "development"
        - name: SERVICE
          value: "elasticsearch"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - -d
        volumeMounts:
        - name: ssh-key
          mountPath: /.ssh
          readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key 
          items:
          - key: authorized-keys
            path: authorized_keys
          - key: id-rsa
            path: id_rsa
          - key: id-rsa.pub
            path: id_rsa.pub
