kind: Service
apiVersion: v1
metadata:
  name: nodejs-joey
  namespace: default
  labels:
    type: nodejs-joey
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    type: nodejs-joey
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-joey
  namespace: default
  labels:
    type: nodejs-joey
spec:
  replicas: 2
  template:
    metadata:
      labels:
        type: nodejs-joey
    spec:
      containers:
      - name: nodejs-joey
        image: 10.0.12.203:32000/joey/nodejs
        #imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8080
