kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    name: es
    nodePort: 32004
  selector:
    app: elasticsearch
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: k8s-registry.zeusis.com:32000/elasticsearch:5.0
        resources:
          limits:
            cpu: 1000m
            memory: 3000Mi
          requests:
            cpu: 1000m
            memory: 3000Mi
