kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: default
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    name: kibana
    nodePort: 32005
  selector:
    app: kibana
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kiabana
        image: k8s-registry.zeusis.com:32000/kibana:5.0
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
        env:
          - name: ELASTICSEARCH_URL
            value: "http://elasticsearch.default.svc.cluster.local:9200"
