kind: Service
apiVersion: v1
metadata:
  name: hadoop-node
  namespace: development
  labels:
    app: hadoop
spec:
  type: NodePort
  ports:
  - port: 8088
    name: yarn
    nodePort: 30005
  selector:
  selector:
    app: hadoop
