apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry
  type: NodePort
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    nodePort: 32000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-registry-v2.5.1
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v2.5.1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v2.5.1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: registry:2.5.1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/domain-crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/domain-key
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        - name: tls-certs
          mountPath: /certs
          readOnly: true
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: kube-registry-pvc
      - name: tls-certs
        secret:
          secretName: kube-registry-tls-certs
          items:
          - key: domain-key
            path: domain-key
          - key: domain-crt
            path: domain-crt
