kind: Service
apiVersion: v1
metadata:
  name: drill-node
  namespace: development
  labels:
    app: drill
spec:
  type: NodePort
  ports:
  - port: 50070
    name: hdfs
    nodePort: 30005
  - port: 16010
    name: hbase
    nodePort: 30006
  - port: 8090
    name: hbase-rest
    nodePort: 30007
  - port: 8046
    name: drill
    nodePort: 30008
  selector:
    app: drill
