kind: Service
apiVersion: v1
metadata:
  name: drill
  namespace: development
  labels:
    app: drill
spec:
  clusterIP: None
  ports:
  - port: 2122
    name: ssh
  selector:
    app: drill
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: drill
  namespace: development
spec:
  replicas: 2
  serviceName: drill
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: drill
    spec:
      nodeSelector:
        type: dell_r610
        #type: virtual
      terminationGracePeriodSeconds: 0
      containers:
      - name: drill
        image: 10.0.12.207:32000/drill:1.8.001
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: 4000Mi
          requests:
            cpu: 2000m
            memory: 4000Mi
        ports:
        # drill
        - containerPort: 31010
        - containerPort: 31011
        - containerPort: 31012
        - containerPort: 8047
        # zk
        - containerPort: 2181
        - containerPort: 2191
        - containerPort: 2192
        # ssh
        - containerPort: 2122
        securityContext:
          privileged: true
        env:
        - name: NAMESPACE
          value: "development"
        - name: SERVICE
          value: "drill"
        - name: HBASE_ZOOKEEPER_QUORUM
          value: "hbase-0.hbase.development.svc.zeusis.com"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - -d
        volumeMounts:
        - name: ssh-key
          mountPath: /.ssh
          readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key 
          items:
          - key: authorized-keys
            path: authorized_keys
          - key: id-rsa
            path: id_rsa
          - key: id-rsa.pub
            path: id_rsa.pub
