kind: Service
apiVersion: v1
metadata:
  name: mariadb
  namespace: development
  labels:
    app: mariadb
spec:
  ports:
  - port: 2122
    name: ssh
  - port: 3310
    name: mysql
  selector:
    app: mariadb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        type: virtual
      containers:
      - name: mariadb
        image: 10.0.12.203:32000/mariadb:10.1.001
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
        ports:
        # ssh
        - containerPort: 2122
        # mysql
        - containerPort: 3310
        env:
        - name: APP_DB
          value: "hive"
        - name: APP_USER
          value: "hive"
        - name: APP_PASSWD
          value: "hive"
        args:
        - -d
        volumeMounts:
        - name: ssh-key
          mountPath: /.ssh
          readOnly: true
#        - name: mariadb-data
#          mountPath: /data
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key 
          items:
          - key: authorized-keys
            path: authorized_keys
#  volumeClaimTemplates:
#  - metadata:
#      name: mariadb-data
#    spec:
#      accessModes:
#      - ReadWriteOnce
#      resources:
#        requests:
#          storage: 1Gi
