apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-prd
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-prd
    spec:
      containers:
      - name: elasticsearch
        image: k8s-registry.zeusis.com:32000/zs/elasticsearch:5.2-alone
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 3000m
            memory: 6000Mi
        volumeMounts:
        - mountPath: /data
          name: elasticsearch-pvc
      volumes:
      - name: elasticsearch-pvc
        persistentVolumeClaim:
          claimName: elasticsearch-pvc-prd
