apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: k8s-registry.zeusis.com:32000/heapster:v1.2.0
        command:
        - /heapster
        - --source=kubernetes:http://192.168.61.2:6550?inClusterConfig=false
        # - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb:8086
