kind: Service
apiVersion: v1
metadata:
  name: push-comet
  namespace: development
  labels:
    system: push
    app: push-comet
spec:
  type: NodePort
  ports:
  - port: 50000
    nodePort: 20000
    name: tcp
  selector:
    system: push
    app: push-comet
---
kind: Service
apiVersion: v1
metadata:
  name: push-comet-inner
  namespace: development
  labels:
    system: push
    app: push-comet
spec:
  clusterIP: None
  ports:
  - port: 50001
    name: websocket
  - port: 50002
    name: rpc
  - port: 50003
    name: tcp
  selector:
    app: push-comet
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: push-comet
  namespace: development
spec:
  replicas: 2
  serviceName: push-comet-inner
  template:
    metadata:
      labels:
        system: push
        app: push-comet
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      nodeSelector:
        type: virtual
      containers:
      - name: push-comet
        image: 10.0.12.203:32000/push-comet:v1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 50004
          name: rpc
        - containerPort: 50005
          name: tcp
