apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: push-downlinkmsg
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: push
        app: push-downlinkms
    spec:
      nodeSelector:
        type: virtual
      containers:
      - name: push-downlinkms
        image: 10.0.12.203:32000/push-downlinkmsg:v1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
        ports:
        - containerPort: 22
          name: ssh
