apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kapacitor
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kapacitor
    spec:
      containers:
      - name: kapacitor
        image: k8s-registry.zeusis.com:32000/kapacitor:1.2.001
        imagePullPolicy: Always
