apiVersion: v1
kind: Service
metadata:
  name: kapacitor
  namespace: default
spec:
  ports:
  - name: http
    port: 9092
  selector:
    app: kapacitor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kapacitor
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kapacitor
    spec:
      containers:
      - name: kapacitor
        image: k8s-registry.zeusis.com:32000/kapacitor:1.2.001
        imagePullPolicy: Always
