apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: monitoring
  labels:
    app: filebeat
spec:
  template:
    metadata:
      labels:
        app: filebeat
      name: filebeat
    spec:
      containers:
      - name: filebeat
        image: k8s-registry.zeusis.com:32000/kube-filebeat:5.0.001
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "192.168.61.2:32004"
          - name: LOG_LEVEL
            value: info
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers
          readOnly: true
        - name: varlogetcd
          mountPath: /var/log/etcd
          readOnly: true
        - name: varlogkubernetes
          mountPath: /var/log/kubernetes
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/containers
      - name: varlogetcd
        hostPath:
          path: /var/log/etcd
      - name: varlogkubernetes
        hostPath:
          path: /var/log/kubernetes
