apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kapacitor-alert-api
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kapacitor-alert-api
    spec:
      containers:
      - name: kapacitor-alert-api
        image: k8s-registry.zeusis.com:32000/zs/kapacitor-alert-api:1.2
        imagePullPolicy: Always
        env:
        - name: MSG_URL
          value: "http://monitor.zeusis.com:8082/alarm/send"
