apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hbase
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hbase
    spec:
      containers:
      - name: hbase
        image: k8s-registry.zeusis.com:32000/zs/hbase:1.2-alone
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 4000Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data
          name: hbase-data
      volumes:
      - name: hbase-data
        persistentVolumeClaim:
          claimName: hbase-sync-pvc
