kind: Service
apiVersion: v1
metadata:
  name: hbase
  namespace: default
  labels:
    app: hbase
spec:
  type: NodePort
  ports:
  - port: 8088
    name: yarn
  - port: 16010
    name: hbase-master
  - port: 9090
    name: hbase-thrift
  - port: 16201
    name: hbase-rest
  selector:
    app: hbase
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hbase
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hbase
    spec:
      containers:
      - name: hbase
        image: k8s-registry.zeusis.com:32000/hbase:1.2-alone.001
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 4000Mi
        securityContext:
          privileged: true
