kind: Service
apiVersion: v1
metadata:
  name: hbase-test1
  namespace: default
  labels:
    type: hbase-test1
spec:
  type: NodePort
  ports:
  - port: 2122
    nodePort: 30001
    name: ssh
  - port: 8020
    name: fs
    nodePort: 30002
  - port: 50020
    name: datanode
    nodePort: 30003
  selector:
    type: hbase-test1
