apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: 10.0.12.207:32000/scylla:1.3
        ports:
        - containerPort: 9042
          name: cql
        - containerPort: 7000
          name: intra-node
        - containerPort: 7199
          name: jmx
        env:
          LISTEN_ADDRESS:
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
