apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: zmon
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
    targetPort: 9042
  selector:
    app: cassandra-data
