# Headless service to provide DNS lookup
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra-data
----
# new API name
apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  # replicas are the same as used by Replication Controllers
  # except pets are deployed in order 0, 1, 2, 3, etc
  replicas: 5
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: cassandra-data
    spec:
      nodeSelector:
        type: virtual
      # just as other component in Kubernetes one
      # or more containers are deployed
      containers:
      - name: cassandra
        image: 10.0.12.203:32000/cassandra
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "4"
            memory: 11Gi
          requests:
           cpu: "4"
           memory: 11Gi
        securityContext:
          privileged: true
        env:
          - name: MAX_HEAP_SIZE
            value: 8192M
          - name: HEAP_NEWSIZE
            value: 2048M
          # this is relying on guaranteed network identity of Pet Sets, we
          # will know the name of the Pets / Pod before they are created
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.default.svc.cluster.local,cassandra-1.cassandra.default.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "OneKDemo"
          - name: CASSANDRA_DC
            value: "DC1-Data"
          - name: CASSANDRA_RACK
            value: "OneKDemo-Rack1-Data"
          - name: CASSANDRA_AUTO_BOOTSTRAP
            value: "false"
          # this variable is used by the read-probe looking
          # for the IP Address in a `nodetool status` command
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
