apiVersion: v1
kind: Service
metadata:
  name: chronograf
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 10000
    nodePort: 32006
  selector:
    app: chronograf
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chronograf
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: k8s-registry.zeusis.com:32000/chronograf
