kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: development
  labels:
    app: postgres
spec:
  ports:
  - port: 5440
    name: pg
  selector:
    app: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: 10.0.12.207:32000/postgres:9.6.001
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
        ports:
        # pg
        - containerPort: 5432
        env:
        - name: PG_INITDB
          value: "true"
        - name: POSTGRES_DB
          value: "rom"
        - name: POSTGRES_USER
          value: "rom"
        - name: POSTGRES_PASSWORD
          value: "rom"
        volumeMounts:
        - name: ssh-key
          mountPath: /.ssh
          readOnly: true
        - name: pg-data
          mountPath: /data
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key 
          items:
          - key: authorized-keys
            path: authorized_keys
      - name: pg-data
        persistentVolumeClaim:
          claimName: postgres-pvc
