apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: default
spec:
  ports:
  - name: http
    port: 8083
  - name: api
    port: 8086
  - name: cluster
    port: 8088
  selector:
    app: influxdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: k8s-registry.zeusis.com:32000/influxdb:1.2.001
        imagePullPolicy: Always
