apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-test
  namespace: default
data:
  config: |
    appname = ota-api
    httpport = 50010
    
    [xorm]
    driver=mysql
    sourcename=ota_app:ota_app@tcp(192.168.60.72:3310)/ota_app?charset=utf8
    showsql=true
    
    [redis]
    addr=192.168.60.2:6388
